### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Brennan-M** [shadowfax6894/CS3753#1]
If it is possible, it would be much appreciated if you would make your OS repositories private. If not, no problem, just thought I would inquire.

**Comment by shadowfax6894** [comment]
I can't make it private because I have a free account, but I can delete it if it's really a problem. Let me know

**Comment by shadowfax6894** [comment]
I only put it up there so employers could see some of my work so sorry if it's been causing problems in your class :O. I'll just take it down actually
